CyRanch_Connect/urls.py
from django.urls import path

from . import views

app_name = 'CyRanch_Connect'

# URL patterns for the CyRanch Connect app
urlpatterns = [
    path('event-checkin/<slug:event_id>', views.event_checkin, name='event_checkin'),
    path('event-qr/<slug:event_id>', views.event_qr, name='event-qr'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name = 'logout'),
    path('prizes/', views.prizes, name='prizes'),
    path('events/', views.events, name='events'),
    path('help/', views.help, name='help'),
    path('report/', views.generate_report, name='report'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('Terms&Conditions/', views.terms),
    path('donate/', views.donate, name='donate'),
    path('Location/', views.location, name='Location'),
]

FBLA_CodingProgramming_2023/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CyRanch_Connect.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CyRanch_Connect/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models


# Student model is connected to a user model which is to be used for authentication
class Student(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE, related_name='student')
    grade = models.IntegerField(null=True, validators=[MinValueValidator(9), MaxValueValidator(12)])
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    student_id = models.IntegerField(null=True)
    email = models.EmailField(max_length=200)
    points = models.IntegerField(blank=True, default=0)

    # Modify metadata for proper representation of the model when it is displayed in the admin panel
    def __str__(self):
        return self.first_name + ' ' + self.last_name

    # Modify the default ordering for the student models in order to quickly find the student with the most points
    class Meta:
        get_latest_by = 'points'


# An event object that stores information about an event, events can be added through the admin panel
class Event(models.Model):
    name = models.CharField(max_length=200, null=True)
    description = models.TextField(max_length=200, blank=True, null=True)
    # The date and time are used in order to only display events that have not happened yet
    date = models.DateTimeField()
    points = models.IntegerField(null=False, default=1)
    location = models.CharField(max_length=200, null=True)
    latitude = models.FloatField(default=0, null=False)
    longitude = models.FloatField(default=0, null=False)
    event_id = models.SlugField(blank=False, null=True)
    # A secret token used to generate ephemeral QR codes for each event
    token = models.IntegerField(default=0, editable=False)
    attendees = models.ManyToManyField(Student, blank=True)

    def __str__(self):
        return self.name


# A prize object, prizes can be added through the admin panel
class Prize(models.Model):
    name = models.CharField(max_length=100, null=True)
    description = models.TextField(blank=True, null=True)
    price = models.IntegerField(blank=False, null=True)
    thumbnail = models.ImageField(upload_to='uploads/', null=True)

    def __str__(self):
        return self.name

CyRanch_Connect/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class CreateStudentForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["password1"].widget.attrs['class'] = "form-control rounded-0 shadow-none"
        self.fields["password2"].widget.attrs['class'] = "form-control rounded-0 shadow-none"
        self.fields["password1"].widget.attrs['name'] = "password"
        self.fields["password2"].widget.attrs['name'] = "password-confirm"
        self.fields["password1"].widget.attrs['id'] = "password"
        self.fields["password2"].widget.attrs['id'] = "password-confirm"

        self.fields['username'].label = 'Community ID'
        self.fields['username'].help_text = 'Required. 6 digits only.'

    def clean_username(self):
        username = self.cleaned_data.get('username')

        if not username.isdigit() or len(username) != 6:
            raise ValidationError("Please enter your 6 digit community code only.")

        return username

    def clean_grade_number(self):
        grade_number = self.cleaned_data.get('grade_number')

        if grade_number and (grade_number < 1 or grade_number > 12):
            raise forms.ValidationError("Grade number must be between 1 and 12.")

        return grade_number

    grade_number = forms.IntegerField(required=False)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2', 'grade_number']
        widgets = {
            'username': forms.TextInput(attrs={'name': "username", 'id': "username", 'class': "form-control rounded-0 shadow-none", 'type': "text"}),
            'first_name': forms.TextInput(attrs={'name': "firstName", 'id': "firstName", 'class': "form-control rounded-0 shadow-none", 'type': "text"}),
            'last_name': forms.TextInput(attrs={'name': "lastname", 'id': "lastname", 'class': "form-control rounded-0 shadow-none", 'type': "text"}),
            'email': forms.EmailInput(attrs={'name': "email", 'id': "email", 'class': "form-control rounded-0 shadow-none ", 'type': "email"}),
            'grade_number': forms.TextInput(attrs={'name': "grade_number", 'id': "grade_number", 'class': "form-control rounded-0 shadow-none", 'type': "text"}),
        }


# A modified version of the default Django PasswordChangeForm
class ChangePasswordForm(PasswordChangeForm):
    # Adding custom styling to the default form elements created by Django
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["old_password"].widget.attrs['class'] = "form-control rounded-0 shadow-none"
        self.fields["new_password1"].widget.attrs['class'] = "form-control rounded-0 shadow-none"
        self.fields["new_password2"].widget.attrs['class'] = "form-control rounded-0 shadow-none"
        self.fields["old_password"].widget.attrs['name'] = "old-password"
        self.fields["new_password1"].widget.attrs['name'] = "new-password"
        self.fields["new_password2"].widget.attrs['name'] = "new-password-confirm"
        self.fields["old_password"].widget.attrs['id'] = "old-password"
        self.fields["new_password1"].widget.attrs['id'] = "new-password"
        self.fields["new_password2"].widget.attrs['id'] = "new-password-confirm"

CyRanch_Connect/views.py
import datetime
import random

from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.utils import timezone
from django.db.models import Avg
from django.db.models.aggregates import StdDev
from django.contrib.auth.decorators import user_passes_test
from django.utils.http import urlencode

from .forms import CreateStudentForm, ChangePasswordForm
from .models import Student, Event, Prize


# Homepage
def index(request):
    return render(request, 'CyRanch_Connect/index.html')


# Events page, only displays events that have not happened yet and events are ordered by date
def events(request):
    events = Event.objects.all().filter(date__gte=timezone.now()).order_by('date')
    return render(request, 'CyRanch_Connect/events.html', {'events': events})


# Shows the prizes that are available each quarter (sorted by number of points needed), prizes can be added through the admin panel
def prizes(request):
    prizes = Prize.objects.all().order_by('price')
    return render(request, 'CyRanch_Connect/prizes.html', {'prizes': prizes})


# A login page, that authenticates a user that is related to a student object in the database.
def login(request):
    if request.method == "POST":
        student_id = request.POST.get('student_id')
        password = request.POST.get('password')

        user = authenticate(request, username=student_id, password=password)

        # Check if a user with provided credentials exists and authenticate them if so
        if user:
            auth_login(request, user)
            messages.success(request, 'Logged in successfully!')
            if request.GET.get('next'):
                return HttpResponseRedirect(request.get('next'))
            else:
                return HttpResponseRedirect(reverse('CyRanch_Connect:index'))
        else:
            messages.error(request, 'Invalid student ID or password')
            return render(request, 'CyRanch_Connect/login.html', {'error': 'Invalid login'})
    else:
        return render(request, 'CyRanch_Connect/login.html')


# An endpoint to log users out
def logout(request):
    auth_logout(request)
    messages.success(request, 'Logged out successfully!')
    return HttpResponseRedirect(reverse('CyRanch_Connect:login'))


# A leaderboard for each grade sorted by the number of points each student has accumulated
def leaderboard(request):
    grade_nine = Student.objects.all().filter(grade=9).order_by('-points')
    grade_ten = Student.objects.all().filter(grade=10).order_by('-points')
    grade_eleven = Student.objects.all().filter(grade=11).order_by('-points')
    grade_twelve = Student.objects.all().filter(grade=12).order_by('-points')

    return render(request, 'CyRanch_Connect/leaderboard.html',
                  {'grade_nine': grade_nine, 'grade_ten': grade_ten, 'grade_eleven': grade_eleven,
                   'grade_twelve': grade_twelve})


# Only for staff members, shows all data and provides useful statistics
def generate_report(request):
    if request.user.is_staff:
        # Data customization for the report
        orderby = request.GET.get('orderby', '-points')
        if orderby not in ['points', '-points', 'first_name', '-first_name', 'last_name', '-last_name']:
            return HttpResponse(status=404)

        # Get all students
        grade_nine = Student.objects.all().filter(grade=9).order_by(orderby)
        grade_ten = Student.objects.all().filter(grade=10).order_by(orderby)
        grade_eleven = Student.objects.all().filter(grade=11).order_by(orderby)
        grade_twelve = Student.objects.all().filter(grade=12).order_by(orderby)

        # Select winners for each grade
        random_winner_nine = random.choice(grade_nine) if grade_nine else "None"
        random_winner_ten = random.choice(grade_ten) if grade_ten else "None"
        random_winner_eleven = random.choice(grade_eleven) if grade_eleven else "None"
        random_winner_twelve = random.choice(grade_twelve) if grade_twelve else "None"

        # Since the latest is set to the points field, calling latest will return the student with the most points
        most_points = Student.objects.latest()

        # Get and format the date
        date = str(datetime.date.today())

        # Generate Statistics
        average = Student.objects.all().aggregate(Avg('points'))['points__avg']
        stddev = Student.objects.all().aggregate(StdDev('points'))['points__stddev']

        return render(request, 'CyRanch_Connect/report.html',
                      {'grade_nine': grade_nine, 'grade_ten': grade_ten, 'grade_eleven': grade_eleven,
                       'grade_twelve': grade_twelve, 'random_winner_nine': random_winner_nine,
                       'random_winner_ten': random_winner_ten, 'random_winner_eleven': random_winner_eleven,
                       'random_winner_twelve': random_winner_twelve, 'most_points': most_points, 'date': date,
                       'average': average, 'stddev': stddev})
    else:
        # Handle a non-staff user attempting to access this page
        messages.error(request, 'You do not have permission to view this page')
        return HttpResponseRedirect(reverse('CyRanch_Connect:index'))


# Interactive help page
def help(request):
    return render(request, 'CyRanch_Connect/help.html')


# Generate QR codes for events, this page may only be accessed by staff members
@user_passes_test(lambda u: u.is_superuser)
def event_qr(request, event_id):
    event = get_object_or_404(Event, event_id=event_id)
    # Creating a random token for the event so that the URL cannot be shared
    event.token = random.randint(100000, 999999)
    event.save()
    qr_url = request.build_absolute_uri(
        f"{reverse('CyRanch_Connect:event_checkin', args={event_id})}?{urlencode({'token': event.token})}")
    return render(request, 'CyRanch_Connect/event_qr.html', {'qr_url': qr_url})


# The page the QR code links to allowing users to claim their points
def event_checkin(request, event_id):
    event = get_object_or_404(Event, event_id=event_id)
    # Ensure the user is logged in, the token is valid, and the user has not already claimed points for this event
    if request.user.is_authenticated:
        if event.token == int(request.GET.get('token')):
            if request.user.student not in event.attendees.all():
                event.attendees.add(request.user.student)
                request.user.student.points += event.points
                request.user.student.save()
                messages.success(request,
                                 f'You have checked in for {event.name} and have earned {event.points} point{"s" if event.points > 1 else ""}!')
                return HttpResponseRedirect(reverse('CyRanch_Connect:index'))
            else:
                messages.error(request, 'You have already checked in to this event')
                return HttpResponseRedirect(reverse('CyRanch_Connect:index'))
        else:
            messages.error(request, 'This QR code has expired, please try again')
            return HttpResponseRedirect(reverse('CyRanch_Connect:index'))
    else:
        messages.error(request, 'You must be logged in to check in to an event')
        return HttpResponseRedirect(reverse('CyRanch_Connect:login'))


from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateStudentForm

from .models import Student

def register(request):
    if request.method == 'POST':
        form = CreateStudentForm(request.POST)
        if form.is_valid():
            user = form.save()  # Save the User instance and get the saved object
            # Create a new Student instance and associate it with the User instance

            student = Student.objects.create(
                user=user,
                first_name=form.cleaned_data['first_name'],
                last_name=form.cleaned_data['last_name'],
                email=form.cleaned_data['email'],
                student_id=int(user.username),
                points=0,
                grade=form.cleaned_data['grade_number']

            )
            return redirect('/login')
    else:
        form = CreateStudentForm()

    return render(request, 'CyRanch_Connect/register.html', {'form': form})



def terms(request):
    # renders the Terms & Conditions
    return render(request, 'CyRanch_Connect/Terms&Conditions.html')

def donate(request):
    # renders the donation page
    return render(request, 'CyRanch_Connect/donate.html')

def location(request):
    # renders the location
    events = Event.objects.all().filter(date__gte=timezone.now()).order_by('date')
    return render(request, 'CyRanch_Connect/Location.html', {'events': events})

CyRanch_Connect/templates/CyRanch_Connect/Location.html
<!DOCTYPE html>
<html class="h-100" lang="en">

{% load static %}

<head>
    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'img/favicon/site.webmanifest' %}">


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    {% block meta %}
    {% endblock %}
    <title>{% block title %}{% endblock %} | Cypress Connect</title>

    <!-- Load Styles -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css">
{#    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">#}
{#    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">#}
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Hind&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:600&amp;display=swap">
    <link rel="stylesheet" href="{% static 'css/Navbar-Centered-Links-icons.css' %}">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">

</head>

<body class="d-flex flex-column h-100">
<!-- Start: Navbar Right Links -->
<nav class="navbar navbar-light navbar-expand-md py-3" style="background: #20296d;">
    <div class="container"><a class="navbar-brand d-xxl-flex align-items-xxl-center"
                              href="{% url 'CyRanch_Connect:index' %}"><img
            src="{% static '\img\Cypress.png' %}" style="height: 100px; width: 100px; margin-right: 10px;"><span
            style="font-size: 25px;font-family: 'Open Sans', sans-serif;color: rgba(255,255,255,0.9);">Cypress Connect</span></a>
        <button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-2"><span
                class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navcol-2">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item"><a class="nav-link active" href="{% url "CyRanch_Connect:donate" %}"
                                        style="color: rgb(255,255,255);font-family: Hind, sans-serif;">Donate</a></li>
                <li class="nav-item"><a class="nav-link active" href="{% url "CyRanch_Connect:Location" %}"
                                        style="color: rgb(255,255,255);font-family: Hind, sans-serif;">Location</a></li>
                <li class="nav-item"><a class="nav-link active" href="{% url "CyRanch_Connect:events" %}"
                                        style="color: rgb(255,255,255);font-family: Hind, sans-serif;">Events</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url "CyRanch_Connect:prizes" %}"
                                        style="color: #ffffff;font-family: Hind, sans-serif;">Prizes</a>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url "CyRanch_Connect:leaderboard" %}"
                                        style="color: rgb(255,255,255);font-family: Hind, sans-serif;">Leaderboard</a></li>
            </ul>
            <div style="padding-left: 10px;">{% if request.user.is_authenticated %}
                <a class="login text-center text-decoration-none" href="#"
                   style="margin-top: 5px;float: left; color: #FFD801; ">
            {% else %}
                <a class="login text-center text-decoration-none" href="{% url 'CyRanch_Connect:login' %}"
                   style="margin-top: 5px; float: left; color: #FFD801;">
            {% endif %}
            <div class="d-flex flex-column">
                <i class="fas fa-user-alt" style="color: #FFD801;"></i>
                {% if request.user.is_authenticated %}
                    <span style="font-family: Hind; font-size: x-small">✪{{ request.user.student.points }} | {% if request.user.is_staff %}Admin{% else %}{{ request.user.student.first_name }}{% endif %}</span>
                {% else %}
                    <span style="font-family: Hind; font-size: x-small">Log In</span>
                {% endif %}</div>
            </a></div>
        </div>
    </div>
</nav>
<!-- End: Navbar Right Links -->

<!-- Custom Message Flashing -->
{% if messages %}
    <!-- Change position:fixed; to prevent floating notifications -->
    <div style="position: absolute; top: 104px; right: 10px; z-index:10; position:fixed;">

        {% for message in messages %}
            {% if message.tags == 'success' %}
                <div class="toast fade show border-0" role="alert" style="display: block; margin-bottom: 5px">
                    <div class="toast-header" style="background: #d5eca8"><i class="fa-solid fa-circle-check"
                                                                             style="margin-right: 7px;color: var(--bs-success);"></i><strong
                            class="me-auto"
                            style="color: #000000;font-family: Hind, sans-serif;">Success</strong><small>1
                        min
                        ago</small>
                        <button class="btn-close ms-2 mb-1 close shadow-none" data-bs-dismiss="toast"></button>
                    </div>
                    <div class="toast-body d-xl-flex justify-content-between align-items-xl-center" role="alert"
                         style="background: #ffffff;">
                        <span style="font-size: 17px; color: #000000;">{{ message }}</span>
                    </div>
                </div>
            {% elif message.tags == 'warning' %}
                <div class="toast fade show border-0" role="alert" style="display: block; margin-bottom: 5px">
                    <div class="toast-header" style="background: #fdfaaa;"><i class="fa-solid fa-circle-exclamation"
                                                                              style="margin-right: 7px;color: var(--bs-warning);"></i><strong
                            class="me-auto"
                            style="color: #000000;font-family: Hind, sans-serif;">Warning</strong><small>1 min
                        ago</small>
                        <button class="btn-close ms-2 mb-1 close shadow-none" data-bs-dismiss="toast"></button>
                    </div>
                    <div class="toast-body d-xl-flex justify-content-between align-items-xl-center" role="alert"
                         style="background: #ffffff"><span
                            style="font-size: 18px;color: #000000;">{{ message }}</span></div>
                </div>
            {% elif message.tags == 'info' %}
                <div class="toast fade show border-0" role="alert" style="display: block; margin-bottom: 5px">
                    <div class="toast-header" style="background: #aaf1fd;">
                        <i class="fa-solid fa-circle-info" style="margin-right: 7px;color: var(--bs-info);"></i><strong
                            class="me-auto"
                            style="color: #000000;font-family: Hind, sans-serif;">Information</strong><small>1 min
                        ago</small>
                        <button class="btn-close ms-2 mb-1 close shadow-none" data-bs-dismiss="toast"></button>
                    </div>
                    <div class="toast-body d-xl-flex justify-content-between align-items-xl-center" role="alert"
                         style="background: #ffffff"><span
                            style="font-size: 18px;color: #000000;">{{ message }}</span></div>
                </div>
            {% elif message.tags == 'error' %}
                <div class="toast fade show border-0" role="alert" style="display: block; margin-bottom: 5px">
                    <div class="toast-header" style="background: #ff9e98;">
                        <i class="fa-solid fa-triangle-exclamation"
                           style="margin-right: 7px;color: var(--bs-danger);"></i>
                        <strong
                                class="me-auto"
                                style="color: #000000;font-family: Hind, sans-serif;">Error</strong><small>1 min
                        ago</small>
                        <button class="btn-close ms-2 mb-1 close shadow-none" data-bs-dismiss="toast"></button>
                    </div>
                    <div class="toast-body d-xl-flex justify-content-between align-items-xl-center" role="alert"
                         style="background: #ffffff"><span
                            style="font-size: 18px;color: #000000;">{{ message }}</span></div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    <script>
        {% for message in messages %}
            $(document).ready(function () {
                $('.toast').toast('show');
            });
        {% endfor %}
    </script>
{% endif %}


{% block content %}
    <html>
        <head>
            <title>Simple Map</title>
            <meta name="viewport" content="initial-scale=1.0">
            <meta charset="utf-8">
            <style>
                /* Always set the map height explicitly to define the size of the div
                 * element that contains the map. */
                #map {
                    height: 200%;
                }
                /* Optional: Makes the sample page fill the window. 29.749907, -95.358421*/
                html, body {
                    height: 100%;
                    margin: 0;
                    padding: 0;
                }
            </style>
        </head>
        <body>
            <div id="map"></div>
            <script>
                var map;
                function initMap() {
                    map = new google.maps.Map(document.getElementById('map'), {
                        center: {lat: 29.939484, lng: -95.719392},
                        zoom: 14
                    });

                    {% for event in events %}
                    var marker = new google.maps.Marker({
                        position: {lat: {{ event.latitude }}, lng: {{ event.longitude }}},
                        map: map,
                        label: '{{ event.name }}'
                    });
                    {% endfor %}
                }
            </script>
            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCPRHqWcKTCMW8hyWmO4aJrhU2ZW9ijlPo&callback=initMap"
                async defer></script>
        </body>
    </html>
{% endblock %}

CyRanch_Connect/templates/CyRanch_Connect/index.html
{% extends "base.html" %}

{% load static %}


{% block title %}Home{% endblock %}


{% block content %}
    <div class="container"><div class="card shadow-lg mx-auto my-5 p-3">
  <div class="card-body">
    <h5 class="card-title">Welcome to Cypress Connect</h5>
    <p class="card-text">Your place to track your participation in community events while earning rewards!</p>
    <a href="{% url 'CyRanch_Connect:events' %}" class="btn  mx-auto " style="background-color: #20296d; color: white">View Events</a>
  </div>
</div></div>


{#    <iframe id="cs-fullscreen-video" class="cs-fullscreen-video" aria-hidden="true" tabindex="-1" allowfullscreen="1"#}
{#            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"#}
{#            title="Web Video"#}
{#            src="https://www.youtube.com/embed/5bSAGeBsxoI?autoplay=1&amp;mute=1&amp;modestbranding=1&amp;controls=0&amp;rel=0&amp;showinfo=0&amp;wmode=opaque&amp;loop=1&amp;playlist=5bSAGeBsxoI&amp;enablejsapi=1&amp;origin=https%3A%2F%2Fwww.cfisd.net&amp;widgetid=1"#}
{#            width="200" height="113" frameborder="0"></iframe>#}
{% endblock %}

CyRanch_Connect/templates/CyRanch_Connect/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Log In{% endblock %}
{% block content %}
<div class="container d-flex justify-content-center align-items-center" style="height: 80vh">
  <div class="card" style="width: 25rem;">
    <div class="card-body">
      <h1 class="card-title text-center mb-4">Log In</h1>
      <form method="POST" action="{% url 'CyRanch_Connect:login' %}" class="needs-validation" id="login-form" novalidate>
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ request.path }}">
        <div class="form-floating mb-3">
          <input name="student_id" id="student_id" class="form-control rounded-0 shadow-none" type="text" placeholder=" " required/>
          <label for="student_id">Student ID</label>
          {% if error %}
            <div class="invalid-feedback">The student ID or password you have entered is invalid.</div>
          {% else %}
            <div class="invalid-feedback">Please enter a valid student ID.</div>
          {% endif %}
        </div>
        <div class="form-floating mb-3">
          <input name="password" id="password" class="form-control rounded-0 shadow-none" type="password" placeholder=" " required/>
          <label for="password">Password</label>
          {% if error %}
            <div class="invalid-feedback">The student ID or password you have entered is invalid.</div>
          {% else %}
            <div class="invalid-feedback">Please enter a valid password.</div>
          {% endif %}
        </div>
        <button class="btn btn-success border rounded-0 shadow-none" type="submit" style="width: 100%;background: #ffd801;color: #000000" onMouseOver="this.style.background='#d9b800'" onMouseOut="this.style.background='#ffd801'" value="Log In">Log In</button>
        <div class="text-center mt-2">
          <p class="mb-0">Don't have an account?</p>
          <a class="link-secondary" href="{% url "CyRanch_Connect:register" %}">Sign-Up here</a>
        </div>
      </form>
      <script>
        (function validate_form() {
          'use strict'
          // Fetch all the forms we want to apply custom Bootstrap validation styles to
          var form = document.getElementById('login-form');
          // Loop over them and prevent submission
          form.addEventListener('submit', function (e) {
            if (!form.checkValidity()) {
              e.preventDefault()
              e.stopPropagation()
            }
            form.classList.add('was-validated')
          }, true)
        })()
      </script>
    </div>
  </div>
</div>
{% endblock %}